### ISSUE TITLE
Merge meeting for Notebook and Lab

### ISSUE THREAD

**Issue by fcollonval** [jupyter/notebook-team-compass#30]
Now that we got the large work of releasing Notebook 7, should we merge the notebook meeting with the JupyterLab one?

What should be the new time for the meeting? The one of JupyterLab?

**Comment by jtpio** [comment]
cc @jupyter/notebook-council for awareness

**Comment by echarles** [comment]
> Now that we got the large work of releasing Notebook 7, should we merge the notebook meeting with the JupyterLab one?

Based on recent activity that was focussed more on Notebook 7 (the JuptyerLab stack) and less on the Notebook 6 / NbClassic work, that sounds a reasonable step.

> What should be the new time for the meeting? The one of JupyterLab?

There are more participants in the JupyterLab calls, so that sounds better. This would also fit better the schedule of the east-coast participants (I guess).

**Comment by ellisonbg** [comment]
Sounds good, would it simplify things if there was a single council as well?

**Comment by jtpio** [comment]
> Sounds good, would it simplify things if there was a single council as well?

This was indeed briefly discussed in one of the notebook calls if I recall correctly. Maybe having a single "Jupyter Frontends" subproject could make sense at some point.

**Comment by jtpio** [comment]
Merging the two meetings could also help put Notebook 7 more on the radar of the regular JupyterLab group. Notebook 7 is pretty much JupyterLab re-assembled in a different way, to folks familiar with JupyterLab development would also be comfortable working on Notebook 7.

This could also help catch potential issues from decisions and technical choices happening upstream in JupyterLab, that can have an impact downstream in Notebook 7. Over the past couple months some changes that landed in JupyterLab required a few extra round-trips and releases because they were breaking Notebook 7 in some way. So again having Notebook 7 on the radar could help prevent such situations, and keep the Notebook 7 use case in mind when designing features or making changes upstream in JupyterLab.

**Comment by ivanov** [comment]
Though I don't usually attend these meetings, I support the conglomeration.

**Comment by jtpio** [comment]
> Sounds good, would it simplify things if there was a single council as well?

Opened https://github.com/jupyterlab/team-compass/issues/230 to discuss this.

**Comment by Zsailer** [comment]
I'm in favor of this. 

Practically speaking, how should we handle the merging of teams and SSC representatives?

For example, I am on the Notebooks Team but not the JupyterLab team. Should we just combine these two teams as one? I would propose we allow every current member to opt-in to joining the inaugural team of "Jupyter Frontends" through a poll.

Right now, @echarles is the Notebook representative and @fcollonval is the Lab representative. Since it's the new year anyways, perhaps we can restart a nomination/voting cycle to pick a representative.

**Comment by echarles** [comment]
> Based on recent activity that was focused more on Notebook 7 (the JupyterLab stack) and less on the Notebook 6 / NbClassic work, that sounds a reasonable step.

I have not read nor heard any feedback on this. Is this silent a green light so we can handle the slowly vanishing need for Notebook 6 / NbClassic?

> Right now, @echarles is the Notebook representative and @fcollonval is the Lab representative. Since it's the new year anyways, perhaps we can restart a nomination/voting cycle to pick a representative.

+1 

FYI a vote to elect a JupyterLab 2024 SSC representative is open since 15 Jan and will en on 30 Jan. @fcollonval Should we pause that vote and waiting on the result of the new opened https://github.com/jupyterlab/team-compass/issues/232 (which formally is just about merging the meetings, not the councils).

**Comment by echarles** [comment]
> FYI a vote to elect a JupyterLab 2024 SSC representative is open since 15 Jan and will en on 30 Jan. @fcollonval Should we pause that vote and wait on the result of the new opened https://github.com/jupyterlab/team-compass/issues/232 (which formally is just about merging the meetings, not the councils) ?

The nomination of the JupyterLab SSC representative has been running since October 2024 and I have already voted a few days ago, so let's just that process continue. As Notebook SSC representative, I will handle the potential merge with the new JupyterLab representative.

**Comment by jtpio** [comment]
Closing as per https://github.com/jupyter/notebook-team-compass/issues/31#issuecomment-1924216280.

And also since the proposal discussed in https://github.com/jupyter/governance/pull/200 has now been approved and merged.

Thanks all!

**Comment by jtpio** [comment]
The Notebook meeting has also now been removed from the Jupyter Google Calendar.
